Fix initializing the database for the first time
Alyetama/internetarchive-youtube pull request #5
Opened 2024-08-29 09:34 UTC by ungeskriptet

The if-else condition was always returning true even though existing_ids was empty. Add an additional check to see if we even have data in the database

2024-08-30 19:14 UTC, Alyetama commented
Thank you for initiating this pull request! I’ve added some comments on one file for your review. I’ll either test the additional commits or wait until the PR is no longer in draft status.

2024-08-31 10:06 UTC, ungeskriptet commented
> I’ve added some comments on one file for your review.

Hi, the PR is now ready. Did you perhaps click on "Start a review" when adding your comments instead of "Add single comment"? I'm not able to see your review comments

2024-09-01 05:14 UTC, Alyetama requested changes

2024-09-01 05:14 UTC, Alyetama commented on internetarchive_youtube/archive_youtube.py
> +            resp = self.upload(video, md, identifier, fname, not self.no_logs)
upload is a static method, so `self` will raise an error. Also, I don't understand the reason behind negating the user selection of `no_logs`.

2024-09-01 05:14 UTC, Alyetama commented on internetarchive_youtube/archive_youtube.py
> +            r = upload(identifier, files=[fname], metadata=md, verbose=verbose)
I don't understand using `verbose` when `verbose` is not used anywhere in the method `upload`.

2024-09-01 05:14 UTC, Alyetama commented on internetarchive_youtube/archive_youtube.py
> +               fname: str, verbose: bool) -> Optional[int]:
Is there a reason to add this argument when it's not referenced anywhere in the function?

2024-09-03 07:53 UTC, ungeskriptet commented on internetarchive_youtube/archive_youtube.py
> +               fname: str, verbose: bool) -> Optional[int]:
Well I'm not a Python export but it's being referenced in line 295 and so on?

2024-09-03 07:56 UTC, ungeskriptet commented on internetarchive_youtube/archive_youtube.py
> +            resp = self.upload(video, md, identifier, fname, not self.no_logs)
Even when logs are enabled it's not possible to see the upload progress and speed. Passing the no_logs boolean here it's possible to make the upload function from the internetarchive library verbose. As for the error, I don't get any.

2025-01-07 14:04 UTC, closed without merging